# Generated by Django 5.0.2 on 2024-02-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helicopter', '0002_category_choper_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='choper',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Вертолеты', 'verbose_name_plural': 'Вертолеты'},
        ),
        migrations.AddField(
            model_name='choper',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='choper',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='helicopter.category'),
        ),
        migrations.AlterField(
            model_name='choper',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
