# Generated by Django 5.0.2 on 2024-02-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helicopter', '0003_alter_category_options_alter_choper_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choper',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
